stages:
  - build
  # - test
  - deploy

variables:
  API_IMAGE: golang:1.15
  GCLOUD_PROJECT_ID: myika-relm

api-build:
  stage: build
  image: $API_IMAGE
  script:
    - go build

# api-unit-test:
#   stage: test
#   image: $API_IMAGE
#   script:
#     - go test

# BATCH DEPLOY

deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCLOUD_KEY
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCLOUD_PROJECT_ID/relm-api-$CI_COMMIT_SHORT_SHA
    - gcloud beta run deploy relm-api --image gcr.io/$GCLOUD_PROJECT_ID/relm-api-$CI_COMMIT_SHORT_SHA --port 8000 --platform managed --min-instances 0 --max-instances 2 --allow-unauthenticated --region asia-southeast1 --memory 128Mi --cpu 1 --concurrency 5 --timeout 1000
